name = "kiwi-archive"
compatibility_date = "2024-01-01"

pages_build_output_dir = "website"

[[d1_databases]]
binding = "DB"
database_name = "serpentshand-db"
database_id = "c1ba95d8-47cc-4bbd-b5ed-3d2c3ebbc84a"
